"""empty message

Revision ID: 15c4f78f08ee
Revises: b7b75bbff211
Create Date: 2016-12-30 04:25:16.082655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c4f78f08ee'
down_revision = 'b7b75bbff211'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
