"""empty message

Revision ID: 5b0b6273a58f
Revises: d8bc77fceae6
Create Date: 2017-01-02 21:22:58.030948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0b6273a58f'
down_revision = 'd8bc77fceae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelapses', sa.Column('frequency', sa.Integer(), server_default='1', nullable=False))
    op.add_column('timelapses', sa.Column('time', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timelapses', 'time')
    op.drop_column('timelapses', 'frequency')
    # ### end Alembic commands ###
