"""empty message

Revision ID: d1edf9ec7ae6
Revises: 15c4f78f08ee
Create Date: 2016-12-31 08:18:53.450192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1edf9ec7ae6'
down_revision = '15c4f78f08ee'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timelapse_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['timelapse_id'], ['timelapses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('timelapses', sa.Column('description', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timelapses', 'description')
    op.drop_table('notes')
    ### end Alembic commands ###
