"""empty message

Revision ID: d8bc77fceae6
Revises: 58d4ba0d9639
Create Date: 2017-01-02 16:51:40.999530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bc77fceae6'
down_revision = '58d4ba0d9639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
